---
name: media
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      # - PUID=1000
      # - PGID=1000
      - VERSION=docker
    volumes:
      - /opt/plex/library:/config
      - /mnt/Media/tvseries:/tv
      - /mnt/Media/movies:/movies
      - /mnt/Media/music:/music
      - /mnt/Media/photos:/photos
      - /mnt/Media/other_videos:/other_videos
    devices:
      - /dev/dri:/dev/dri
    user: root
    restart: unless-stopped

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    # user: 1000:1000
    network_mode: host
    volumes:
      - /opt/jellyfin/config:/config
      - /opt/jellyfin/cache:/cache
      - type: bind
        source: /mnt/Media
        target: /media
        read_only: true
    user: root
    restart: unless-stopped
    # # Optional - alternative address used for autodiscovery
    # environment:
    #   - JELLYFIN_PublishedServerUrl=http://example.com
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
    extra_hosts:
      - 'host.docker.internal:host-gateway'

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: host
    volumes:
      - /opt/prowlarr/config:/config
    ports:
      - "9696:9696"
    user: root
    restart: unless-stopped

  radarr: 
    image: lscr.io/linuxserver/radarr:latest 
    container_name: radarr 
    network_mode: host
    environment: 
      - PUID=0 
      - PGID=0 
    volumes: 
      - /opt/radarr/config:/config 
      - /mnt/Media:/mnt/media 
      - /mnt/Media/movies:/mnt/downloads 
    ports: 
      - 7878:7878 
    user: root
    restart: unless-stopped 

  sonarr: 
    image: lscr.io/linuxserver/sonarr:latest 
    container_name: sonarr 
    network_mode: host
    environment: 
      - PUID=0 
      - PGID=0 
    volumes: 
      - /opt/sonarr/config:/config 
      - /mnt/Media:/mnt/media 
      - /mnt/Media/tvseries:/mnt/downloads
    ports: 
      - 8989:8989 
    user: root
    restart: unless-stopped

  readarr: 
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr 
    network_mode: host
    environment: 
      - PUID=0 
      - PGID=0 
      - TZ=Asia/Calcutta
    volumes: 
      - /opt/readarr/config:/config 
      - /mnt/Media:/mnt/media 
      - /mnt/Media/ebooks:/mnt/downloads
    ports: 
      - 8787:8787 
    user: root
    restart: unless-stopped 

  qbittorrent: 
    image: lscr.io/linuxserver/qbittorrent:latest 
    container_name: qbittorrent 
    network_mode: host
    environment: 
      - PUID=0 
      - PGID=0 
      - WEBUI_PORT=8090 
    volumes: 
      - /opt/qbittorrent/config:/config 
      - /mnt/Media/movies:/downloads/radarr
      - /mnt/Media/tvseries:/downloads/tv-sonarr
    ports: 
      - 8090:8080 
      - 6881:6881 
      - 6881:6881/udp 
    user: root
    restart: unless-stopped 
