---
name: network-tools
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: host
    environment:
      - PIHOLE_DOMAIN=pihole.internal.home
      - VIRTUAL_HOST=pihole.internal.home
      - FTLCONF_LOCAL_IPV4=192.168.1.123
      - WEB_BIND_ADDR=192.168.1.123
      - DHCP_ACTIVE=true
      - DHCP_START=192.168.1.100
      - DHCP_END=192.168.1.149
      - DHCP_ROUTER=192.168.1.1
      - INTERFACE=eno2
      - FTLCONF_webserver_port=8080
      - RATE_LIMIT=0/0
    volumes:
      - /opt/pihole/config:/etc/pihole
      - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
    user: root
    restart: unless-stopped

  nginx-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy
    user: root
    restart: unless-stopped
    network_mode: host
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - /opt/nginx-proxy/nginx.conf:/etc/nginx/nginx.conf
      - /opt/nginx-proxy/conf.d:/etc/nginx/conf.d
      - /opt/nginx-proxy/data:/data
      - /opt/nginx/certs:/etc/nginx/certs:ro
      - /opt/nginx-proxy/letsencrypt:/etc/letsencrypt

  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    restart: unless-stopped
    network_mode: host
    environment:
      - TS_AUTHKEY=tskey-auth-kdH1Wb3Xa521CNTRL-m17PjFRS7AKgGus4NH6MAKoBoRFvYHrj
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - /opt/tailscale:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin