- name: Install Samba packages
  apt:
    name: samba
    state: present
    update_cache: yes

- name: Configure Samba
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    mode: '0644'
    owner: root
    group: root
  notify: Restart Samba

- name: Ensure Samba service is running
  service:
    name: smbd
    state: started
    enabled: true
